language: node_js
node_js:
  - v16.14.0
before_deploy:
  - rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install faraday -v 1.10.2

script:
  - "npm run build"
  - "npm run test:nowatch"
deploy:
  provide: heroku
  api_key: $HEROKU_TOKEN
  app: "book-store-webui"
  on:
    branch: main